Now we have 14 model

For this notebook we will put our picture through ALL the 14 model

and we will then take the three highest (1's) valued models

    by having a 2Darray that hold 14 models x [0 , 1] (softmax) 

function1(){
    return arrayofVal.appended
}

function2(){
    takes poster and turns it into np.array
}

function3(){
    takes arrayOfVals
    returns best three genres with their percentages
}

main(){
input = poster

function2(poster)
arrayyofVals = []
arrayofVals.append (function1(poster, comedy))
function1(poster, action)
function1(poster, horror)
function1(poster, ...)
function1(poster, ...)
function1(poster, ...)
function1(poster, 14...)


function3()


done :)


}


In [1]:
from PIL import Image
import pandas as pd
import numpy as np
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, Flatten, Dropout
from keras.models import Sequential
from keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import os
import tensorflow as tf
from tensorflow import keras
import imdb

In [2]:
def PosterToArray(image):
    poster = np.array(image)
    poster = poster.astype('float32') / 255
    return poster

In [3]:
def PredictByModel(ourGenre, posterPath):

    poster = Image.open(posterPath)
    poster = poster.resize((100,100))
    numPyPoster = PosterToArray(poster)
    posterArray = [numPyPoster]
    posterArray = np.array(posterArray) 
    checkpoint_path = f"Weights/{ourGenre}/cp.ckpt"

    model = Sequential()
    model.add(Conv2D(64, (3, 3), activation='relu', padding='same', input_shape=(100, 100, 3)))
    model.add(MaxPooling2D((2, 2), padding='same'))
    model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2), padding='same'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(2, activation="softmax"))
    model.compile(optimizer='adam', loss='CategoricalCrossentropy', metrics=["accuracy"])

    model.load_weights(checkpoint_path).expect_partial()
    
    predicted = model.predict(posterArray)
    return (predicted[0], ourGenre)
    
    

In [4]:
def PredictAllModes(posterPath, allPredictions):
    Genres = ['Action', 'Adventure', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Horror', 'Music', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller']
    for i in range(len(Genres)):
        allPredictions.append(PredictByModel(Genres[i], posterPath, allPredictions))
    return allPredictions

In [5]:
recommendedGenres = []

In [6]:
def ThreeGenres(allPredictions):
    tempSort = []
    
    for i in range(len(allPredictions)):
        temp = [allPredictions[i][0][1] , allPredictions[i][1]]
        tempSort.append(temp)
    tempSort.sort()
    tempSort.reverse()
    print(f"Genre1: {tempSort[0][1]} ({np.round((tempSort[0][0] * 100),2)}%)    Genre2: {tempSort[1][1]} ({np.round(tempSort[1][0] * 100,2)}%)    Genre3: {tempSort[2][1]}({np.round(tempSort[2][0] * 100,2)}%)")
    recommendedGenres.append(tempSort[0][1])
    recommendedGenres.append(tempSort[1][1])
    recommendedGenres.append(tempSort[2][1])
    

In [7]:
def recommendation():
    movies = imdb.IMDb()
    top250 = movies.get_top250_movies()
    #recommendedGenres.append("Crime")

    # the first 20 movies in the top 250
    for movie_count in range(0, 20):
        
        movie = movies.get_movie(top250[movie_count].movieID)
        genre = movie['genres'][0]
        
        
        if genre in recommendedGenres:
            title = movie['title']
        
            print(f"Looking for another {genre} movie? try {title}.")

In [32]:
Genres = ['Action', 'Adventure', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Horror', 'Music', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller']
posterPath = f"test8.jpg"
allPredictions = []
for i in range(len(Genres)):
    allPredictions.append(PredictByModel(Genres[i], posterPath))
allPredictions

[(array([4.6254561e-04, 9.9953747e-01], dtype=float32), 'Action'),
 (array([0.40577826, 0.5942217 ], dtype=float32), 'Adventure'),
 (array([0.95893425, 0.04106576], dtype=float32), 'Comedy'),
 (array([0.99869955, 0.00130049], dtype=float32), 'Crime'),
 (array([0.5232533 , 0.47674662], dtype=float32), 'Documentary'),
 (array([0.99844164, 0.00155839], dtype=float32), 'Drama'),
 (array([0.7874962 , 0.21250382], dtype=float32), 'Family'),
 (array([0.6490384 , 0.35096163], dtype=float32), 'Fantasy'),
 (array([0.80444187, 0.1955581 ], dtype=float32), 'Horror'),
 (array([0.54034185, 0.4596582 ], dtype=float32), 'Music'),
 (array([0.6097088 , 0.39029124], dtype=float32), 'Mystery'),
 (array([0.6130327 , 0.38696736], dtype=float32), 'Romance'),
 (array([0.09741608, 0.90258396], dtype=float32), 'Sci-Fi'),
 (array([0.12414116, 0.87585884], dtype=float32), 'Thriller')]

In [33]:
ThreeGenres(allPredictions)


Genre1: Action (99.95%)    Genre2: Sci-Fi (90.26%)    Genre3: Thriller(87.59%)


In [ ]:
recommendation()
        