In [59]:
import pandas as pd
import numpy as np

In [5]:
dfArray = []

In [6]:
for i in range (1980, 2016):
    temp = pd.read_csv(f"csvData/{i}.csv")
    dfArray.append(temp)

In [96]:
len(dfArray)

36

In [28]:
for i in range(len(dfArray)):
    dfArray[i]['Genre'] = dfArray[i]['Genre'].str.split(', ')

In [99]:
len(dfArray[0]['Genre'][0])

3

In [34]:
genre =[]
imdbId = []

In [35]:
for i in range(len(dfArray)):
    for j in range(len(dfArray[i])):
        genre.append(dfArray[i]['Genre'][j])
        imdbId.append(dfArray[i]['imdbID'][j])


In [36]:
genre

[['Action', 'Adventure', 'Fantasy'],
 ['Comedy', 'Crime'],
 ['Comedy'],
 ['Action', 'Comedy'],
 ['Comedy', 'War'],
 ['Biography', 'Drama', 'Music'],
 ['Action', 'Comedy'],
 ['Adventure', 'Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Adventure', 'Comedy', 'Family'],
 ['Drama', 'Romance', 'Western'],
 ['Drama', 'Horror'],
 ['Comedy', 'Romance'],
 ['Comedy', 'Crime', 'Sci-Fi'],
 ['Comedy', 'Sport'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Mystery', 'Thriller'],
 ['Drama', 'Music', 'Romance'],
 ['Action', 'Adventure', 'Sci-Fi'],
 ['Biography', 'Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Biography', 'Drama', 'Sport'],
 ['Fantasy', 'Musical', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Comedy', 'Drama', 'Family'],
 ['Fantasy', 'Horror'],
 ['Horror', 'Sci-Fi', 'Thriller'],
 ['Crime', 'Mystery', 'Thriller'],
 ['Action', 'Drama', 'Romance'],
 ['Music', 'Romance', 'Drama'],
 ['Adventure', 'Comedy', 'Family'],
 ['Adventure', 'Comedy', 'Crime'],
 ['Action', 'Sci-Fi'],
 [

In [37]:
imdbId

['tt0080684',
 'tt0081562',
 'tt0080339',
 'tt0080377',
 'tt0081375',
 'tt0080549',
 'tt0081529',
 'tt0080453',
 'tt0080455',
 'tt0081283',
 'tt0081353',
 'tt0081696',
 'tt0081505',
 'tt0081480',
 'tt0080520',
 'tt0080487',
 'tt0080474',
 'tt0081060',
 'tt0080661',
 'tt0080948',
 'tt0080745',
 'tt0080678',
 'tt0080472',
 'tt0081398',
 'tt0081777',
 'tt0080365',
 'tt0081207',
 'tt0080749',
 'tt0080360',
 'tt0080569',
 'tt0081259',
 'tt0080888',
 'tt0080861',
 'tt0081439',
 'tt0080736',
 'tt0080907',
 'tt0080863',
 'tt0081071',
 'tt0080739',
 'tt0081383',
 'tt0081249',
 'tt0081268',
 'tt0080556',
 'tt0081751',
 'tt0081032',
 'tt0081698',
 'tt0081163',
 'tt0081031',
 'tt0080731',
 'tt0081554',
 'tt0080881',
 'tt0081485',
 'tt0081534',
 'tt0081656',
 'tt0079285',
 'tt0080754',
 'tt0080402',
 'tt0080724',
 'tt0080756',
 'tt0080437',
 'tt0081568',
 'tt0081748',
 'tt0080808',
 'tt0081184',
 'tt0081063',
 'tt0081269',
 'tt0080634',
 'tt0080850',
 'tt0080550',
 'tt0081758',
 'tt0081150',
 'tt00

In [87]:
genreFirst = []

In [85]:
len(genre)

8873

In [88]:
#take only first genre
#takes a long time relatve to other code for iterating 
for i in range(len(genre)):
    try:
        genreFirst.append(genre[i][0])
    except:
        genreFirst.append(genre[i])
        continue 

In [89]:
len(genreFirst)

8873

In [51]:
GenreString = []

In [52]:
for i in range(len(genreFirst)):
    if genreFirst[i] not in GenreString:
        GenreString.append(genreFirst[i])

In [53]:
GenreString

['Action',
 'Comedy',
 'Biography',
 'Adventure',
 'Drama',
 'Mystery',
 'Fantasy',
 'Crime',
 'Horror',
 'Music',
 'Western',
 'Documentary',
 'Family',
 'Animation',
 'Romance',
 'Musical',
 'Sci-Fi',
 'Thriller',
 'Short',
 'War',
 'Adult',
 'Reality-TV',
 nan,
 'Game-Show',
 'History',
 'News',
 'Sport',
 'Talk-Show']

In [54]:
for i in range (len(GenreString) -1, 0 ,-1): #had a nan value
    if not isinstance(GenreString[i], str):
        GenreString.pop(i)
GenreString

['Action',
 'Comedy',
 'Biography',
 'Adventure',
 'Drama',
 'Mystery',
 'Fantasy',
 'Crime',
 'Horror',
 'Music',
 'Western',
 'Documentary',
 'Family',
 'Animation',
 'Romance',
 'Musical',
 'Sci-Fi',
 'Thriller',
 'Short',
 'War',
 'Adult',
 'Reality-TV',
 'Game-Show',
 'History',
 'News',
 'Sport',
 'Talk-Show']

In [55]:
len(GenreString)

27

In [90]:
genreCounter = np.zeros(len(GenreString), dtype=object)
genreCounter

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0], dtype=object)

In [67]:
tempGenre = []

In [68]:
for i in range(len(genre)):
    try:
        for j in range(len(genre[i])):
            tempGenre.append(genre[i][j])
    except:
        tempGenre.append(genre[i])
tempGenre


['Action',
 'Adventure',
 'Fantasy',
 'Comedy',
 'Crime',
 'Comedy',
 'Action',
 'Comedy',
 'Comedy',
 'War',
 'Biography',
 'Drama',
 'Music',
 'Action',
 'Comedy',
 'Adventure',
 'Drama',
 'Romance',
 'Action',
 'Comedy',
 'Crime',
 'Drama',
 'Adventure',
 'Comedy',
 'Family',
 'Drama',
 'Romance',
 'Western',
 'Drama',
 'Horror',
 'Comedy',
 'Romance',
 'Comedy',
 'Crime',
 'Sci-Fi',
 'Comedy',
 'Sport',
 'Drama',
 'Comedy',
 'Drama',
 'Mystery',
 'Thriller',
 'Drama',
 'Music',
 'Romance',
 'Action',
 'Adventure',
 'Sci-Fi',
 'Biography',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Biography',
 'Drama',
 'Sport',
 'Fantasy',
 'Musical',
 'Romance',
 'Crime',
 'Drama',
 'Mystery',
 'Comedy',
 'Drama',
 'Family',
 'Fantasy',
 'Horror',
 'Horror',
 'Sci-Fi',
 'Thriller',
 'Crime',
 'Mystery',
 'Thriller',
 'Action',
 'Drama',
 'Romance',
 'Music',
 'Romance',
 'Drama',
 'Adventure',
 'Comedy',
 'Family',
 'Adventure',
 'Comedy',
 'Crime',
 'Action',
 'Sci-Fi',
 'Action',
 'Biograp

In [71]:
len(GenreString)

27

In [72]:
genreCounter2 = np.zeros(len(GenreString), dtype=object)
len(genreCounter2)

27

In [73]:
len(tempGenre)

20147

In [91]:
for i in range(len(genreFirst)):
    for j in range(len(GenreString)):
        if genreFirst[i] == GenreString[j]:
            genreCounter[j]+= 1
genreCounter

array([1436, 2505, 342, 371, 1645, 37, 63, 460, 267, 16, 8, 924, 34, 286,
       34, 13, 20, 54, 256, 5, 38, 9, 3, 3, 2, 3, 2], dtype=object)

In [75]:
for i in range(len(tempGenre)):
    for j in range(len(GenreString)):
        if tempGenre[i] == GenreString[j]:
            genreCounter2[j]+= 1
genreCounter2

array([1534, 3358, 528, 1003, 4225, 526, 533, 1322, 615, 370, 60, 934,
       509, 298, 1496, 127, 466, 1050, 367, 164, 38, 11, 3, 281, 29, 259,
       4], dtype=object)

CSV     imdbID   GENRE


        1       1  2   3





        1       1
        1       2
        1       3

        wad7a ya5wana3

In [79]:
for i in range(len(GenreString)):
    if genreCounter2[i] > 400:
        print(f"Genre: {GenreString[i]} Size: {genreCounter2[i]}")

Genre: Action Size: 1534
Genre: Comedy Size: 3358
Genre: Biography Size: 528
Genre: Adventure Size: 1003
Genre: Drama Size: 4225
Genre: Mystery Size: 526
Genre: Fantasy Size: 533
Genre: Crime Size: 1322
Genre: Horror Size: 615
Genre: Documentary Size: 934
Genre: Family Size: 509
Genre: Romance Size: 1496
Genre: Sci-Fi Size: 466
Genre: Thriller Size: 1050


In [95]:
for i in range(len(GenreString)):
    if genreCounter[i] > 0:
        print(f"Genre: {GenreString[i]} Size: {genreCounter[i]}")

Genre: Action Size: 1436
Genre: Comedy Size: 2505
Genre: Biography Size: 342
Genre: Adventure Size: 371
Genre: Drama Size: 1645
Genre: Mystery Size: 37
Genre: Fantasy Size: 63
Genre: Crime Size: 460
Genre: Horror Size: 267
Genre: Music Size: 16
Genre: Western Size: 8
Genre: Documentary Size: 924
Genre: Family Size: 34
Genre: Animation Size: 286
Genre: Romance Size: 34
Genre: Musical Size: 13
Genre: Sci-Fi Size: 20
Genre: Thriller Size: 54
Genre: Short Size: 256
Genre: War Size: 5
Genre: Adult Size: 38
Genre: Reality-TV Size: 9
Genre: Game-Show Size: 3
Genre: History Size: 3
Genre: News Size: 2
Genre: Sport Size: 3
Genre: Talk-Show Size: 2
